# Generated by Django 4.2.7 on 2025-09-29 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlanguagepreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='translationcache',
            index=models.Index(fields=['source_language', 'target_language'], name='translation_source__d396d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='translationcache',
            unique_together={('original_text', 'source_language', 'target_language')},
        ),
    ]
