# Generated by Django 4.2.7 on 2025-09-29 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectitem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='learning.subjectgroup'),
        ),
        migrations.AddField(
            model_name='studytext',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='learning.page'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.examsession'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.subject'),
        ),
        migrations.AddField(
            model_name='page',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='learning.chapter'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='learning.word'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='exam_sessions', to='learning.subject'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.examyear'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.question'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='learning.subjectitem'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'subject', 'item', 'chapter', 'page', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together={('word', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('year', 'session_number')},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'choice_number')},
        ),
    ]
