# Generated by Django 4.2.7 on 2025-09-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group_key', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subject_groups',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='examsession',
            options={'ordering': ['-year__year', '-session_number']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['group__order', 'order', 'name']},
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='available_subjects',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='group_key',
        ),
        migrations.AddField(
            model_name='examsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='examsession',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='exam_sessions', to='learning.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='learning.subjectgroup'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.examyear'),
        ),
    ]
