# Generated by Django 4.2.7 on 2025-09-30 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KotobaCategory',
            fields=[
                ('category_key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('japanese_name', models.CharField(max_length=200)),
                ('indonesian_translation', models.CharField(max_length=200)),
                ('ruby_reading', models.CharField(max_length=200)),
                ('order_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kotoba_categories',
                'ordering': ['order_number', 'japanese_name'],
            },
        ),
        migrations.CreateModel(
            name='KotobaExample',
            fields=[
                ('example_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('japanese_example', models.TextField()),
                ('indonesian_example', models.TextField()),
                ('order_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kotoba_examples',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='KotobaSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_key', models.CharField(max_length=100)),
                ('japanese_name', models.CharField(max_length=200)),
                ('indonesian_translation', models.CharField(max_length=200)),
                ('ruby_reading', models.CharField(max_length=200)),
                ('order_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='learning.kotobacategory')),
            ],
            options={
                'db_table': 'kotoba_subcategories',
                'ordering': ['order_number', 'japanese_name'],
                'unique_together': {('main_category', 'subcategory_key')},
            },
        ),
        migrations.CreateModel(
            name='KotobaWord',
            fields=[
                ('word_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('japanese_word', models.CharField(max_length=200)),
                ('ruby_reading', models.CharField(max_length=200)),
                ('indonesian_translation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='learning.kotobacategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='learning.kotobasubcategory')),
            ],
            options={
                'db_table': 'kotoba_words',
                'ordering': ['japanese_word'],
            },
        ),
        migrations.CreateModel(
            name='KotobaVocabulary',
            fields=[
                ('vocabulary_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('japanese_word', models.CharField(max_length=200)),
                ('ruby_reading', models.CharField(max_length=200)),
                ('indonesian_translation', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='learning.kotobaexample')),
            ],
            options={
                'db_table': 'kotoba_vocabulary',
                'ordering': ['japanese_word'],
            },
        ),
        migrations.AddField(
            model_name='kotobaexample',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='learning.kotobaword'),
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_memorized', models.BooleanField(default=False)),
                ('review_count', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.kotobaword')),
            ],
            options={
                'db_table': 'user_word_progress',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
